### ISSUE TITLE
Explore insertAdjacentHTML

### ISSUE THREAD

**Issue by rianby64** [m3co/pseudoimport-html#30]
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML

**Comment by rianby64** [comment]
It breaks the promises and everything else... Let's close it

**Comment by Anomeon** [comment]
Think about this feature implementation

**Comment by rianby64** [comment]
Currently we're using ```Range.createContextualFragment``` as factory for HTML fetched content.

**Comment by rianby64** [comment]
So, the question around this issue is if we need to define where to place the HTML fetched content?
Let's expose this issue by an example
```html
<div class="mdl-fragment" src="URL">
  innerHTML
</div>
```

The question is: what we should do with ```innerHTML```? Replace with HTML fetched content? Conserve by appending HTML fetched to the parent ```div```?

**Comment by rianby64** [comment]
Plus and cons
+ ```insertAdjacentHTML``` works from IE4 - so in terms of compatibility this function is better than ```createContextualFragment```
\- ```insertAdjacentHTML``` breaks the fetch mechanism based on _Promise_

**Comment by rianby64** [comment]
[This commit kills this idea at all](https://github.com/m3co/pseudoimport-html/commit/13f3c662ffa5526ac2705f8b1ec03bf8d51b4b6a)...
