### ISSUE TITLE
Sub-route is not working correctly

### ISSUE THREAD

**Issue by Spaider15** [m3co/pseudoimport-html#36]
Hello @rianby64,

When i open url below, this route will open : #hash1/hash3/hash5/hash7, but this is not expectable behaviour. Thanks.
http://router2-demo.m3c.space/demo/demo-simple.html#/hash7

**Comment by rianby64** [comment]
Bug! Thanks a lot!

**Comment by rianby64** [comment]
Closing as this issue doesn't belong to pseudomiport but to router3
