### ISSUE TITLE
Fix the documentation in order to cover fragment-wc

### ISSUE THREAD

**Issue by rianby64** [m3co/pseudoimport-html#50]
Currently the documentation covers _fragment-mdl_, and _fragment-ce_, but _fragment-wc_ is not being covered. Is anybody there who can give me a tip?

**Comment by rianby64** [comment]
Jsdoc3 looks to be incompatible with _@@include_ keyword and its behavior involved with...

**Comment by Anomeon** [comment]
Memo: replace HTMLXFragmentElement in fragment-wc with another right keyword

**Comment by rianby64** [comment]
I just noticed that CE and WC are the same. Maybe would be enough to include both as a single element?

**Comment by rianby64** [comment]
From now, using ```<link rel="import">```
