### ISSUE TITLE
Catch the errors that may occur while executing an script

### ISSUE THREAD

**Issue by rianby64** [m3co/pseudoimport-html#59]
[This line](https://github.com/m3co/pseudoimport-html/blob/2490ec33ce31b9d8eaa7b0d7ae2201f601f5d8ee/src/fragment-ce.js#L308) may arise a lot of errors that you should expose in a proper manner. E.g. if a script has a syntactic mistake.

**Comment by rianby64** [comment]
As per #40 we've meta-tags for _fetch_. I'm wondering... should these meta-tags affect the _fetch_ function that [requests the scripts](https://github.com/m3co/pseudoimport-html/blob/2490ec33ce31b9d8eaa7b0d7ae2201f601f5d8ee/src/fragment-ce.js#L302)?

**Comment by Anomeon** [comment]
Need review 5d6db58, 		579c56f

**Comment by rianby64** [comment]
From now, using ```<link rel="import">```
