### ISSUE TITLE
Explore compatibility of fragments with import and export mechanism

### ISSUE THREAD

**Issue by Anomeon** [m3co/pseudoimport-html#60]
Let's suppose we have fragment would be load es2015 modules. What's happen when fragment load it? How it register and specify order of loading? Now, let's add some code... Code below works in Safari TP Release 24:

index.html
```html
<body>
  <script src="fragment-ce.js"></script>
  <x-fragment src="x-fragment.html"></x-fragment>
</body>
```

x-fragment.html
```html
<!DOCTYPE html>
<script type="module">
  import {myVar} from './export.js';

  console.log(myVar);
</script>
```

export.js
```js
export let myVar = 1;
```

**Comment by rianby64** [comment]
https://github.com/w3c/web-platform-tests/tree/master/html/semantics/scripting-1/the-script-element/module

Исследовать этот вопрос относительно стандарта

**Comment by rianby64** [comment]
From now, using ```<link rel="import">```
