### ISSUE TITLE
Process the URI schemes properly

### ISSUE THREAD

**Issue by rianby64** [m3co/pseudoimport-html#65]
Schemes like ```http://``` or ```https://``` are being ignored completely by [preparePath](https://github.com/m3co/pseudoimport-html/blob/57043045f2431c7db66967ce7e30d025d8d3628b/includes/utils.js#L25).

Let's try to fix it up by including a list of schemes.

**Comment by Anomeon** [comment]
If x-fragment has cross-origin src, we have a problem with sources in x-fragment files. We must set src with URL schemes and origins.
